services:

  testing:
    image: nexus:5000/cicd/testing
    build:
      dockerfile: docker/testing/Dockerfile
      context: .
    ports:
      - "8090:8080"

  production:
    image: nexus:5000/cicd/testing
    build:
      dockerfile: docker/production/Dockerfile
      context: .
    ports:
      - "8091:8080"
  nexus:
    image: sonatype/nexus3

    networks:
      - jenkins

    volumes:
      - nexus-data:/nexus-data

    ports:
      - "8081:8081"
      - "5000:5000"

volumes:
  nexus-data:

networks:
  jenkins:
    external: true