services:

  nexus:
    image: sonatype/nexus3

    networks:
      - jenkins

    volumes:
      - nexus-data:/nexus-data

    ports:
      - "8081:8081"
      - "5000:5000"

volumes:
  nexus-data:

networks:
  jenkins:
    external: true